### ISSUE TITLE
企画書「ポムポムプリン」

### ISSUE THREAD

**Issue by Fanogia** [katsube/neec2019A#32]
4列目
[企画書_ポムポムプリン_20190617.xlsx](https://github.com/katsube/neec2019A/files/3295498/_._20190617.xlsx)

**Comment by Fanogia** [comment]
[企画書_ポムポムプリン_20190617.xlsx](https://github.com/katsube/neec2019A/files/3319556/_._20190617.xlsx)

**Comment by katsube** [comment]
GitHubのURLの提出お願いしますね。
このチケットに書き込んでもらえば大丈夫です。

**Comment by Fanogia** [comment]
https://github.com/kou03/Bomb

**Comment by katsube** [comment]
提出お疲れ様です。
GitHubのURL了解です。Wikiにも反映しました。

[オンライン対戦](https://github.com/katsube/neec2019A/wiki/%E3%82%AA%E3%83%B3%E3%83%A9%E3%82%A4%E3%83%B3%E5%AF%BE%E6%88%A6)
