### ISSUE TITLE
企画書「じこはおこるさ」

### ISSUE THREAD

**Issue by nindori10** [katsube/neec2019A#33]
2列目

**Comment by nindori10** [comment]
[企画書「じこはおこるさ」20190617.xlsx](https://github.com/katsube/neec2019A/files/3295508/20190617.xlsx)

**Comment by katsube** [comment]
GitHubのリポジトリのURLの提出もお願いしますね。
ここに書き込んでもらえればOKです。

**Comment by nindori10** [comment]
[企画書「じこはおこるさ」20190617.xlsx](https://github.com/katsube/neec2019A/files/3390618/20190617.xlsx)リポジトリ追加しました。
ゲームの企画も決まりました。よろしくお願いします。

**Comment by katsube** [comment]
提出お疲れ様です。
Wikiにも反映しています。

[オンライン対戦](https://github.com/katsube/neec2019A/wiki/%E3%82%AA%E3%83%B3%E3%83%A9%E3%82%A4%E3%83%B3%E5%AF%BE%E6%88%A6)
