### ISSUE TITLE
企画書[タピる？]

### ISSUE THREAD

**Issue by FukudaTsubasa** [katsube/neec2019A#34]
[企画書_タピる？_20190617.xlsx](https://github.com/katsube/neec2019A/files/3295502/_._20190617.xlsx)

**Comment by FukudaTsubasa** [comment]
６列目の真ん中

**Comment by FukudaTsubasa** [comment]
更新
[企画書_タピる？_20190617.xlsx](https://github.com/katsube/neec2019A/files/3319623/_._20190617.xlsx)

**Comment by FukudaTsubasa** [comment]
プロダクトバックログ
[ProductBackLog.xlsx](https://github.com/katsube/neec2019A/files/3319628/ProductBackLog.xlsx)

**Comment by KTK33** [comment]
[ProductBackLog.xlsx](https://github.com/katsube/neec2019A/files/3391184/ProductBackLog.xlsx)

プロダクトバッグを更新しました。確認お願い致します。

**Comment by KTK33** [comment]
[企画書_タピる？_20190617.xlsx](https://github.com/katsube/neec2019A/files/3391208/_._20190617.xlsx)

企画書を更新しました。確認よろしくお願い致します。

**Comment by katsube** [comment]
提出お疲れ様です。
Wikiにも反映しました。

[オンライン対戦](https://github.com/katsube/neec2019A/wiki/%E3%82%AA%E3%83%B3%E3%83%A9%E3%82%A4%E3%83%B3%E5%AF%BE%E6%88%A6)
