### ISSUE TITLE
企画書「3BaCarnival」

### ISSUE THREAD

**Issue by hayato310** [katsube/neec2019A#35]
[企画書_3BaCarnival_20190617.xlsx](https://github.com/katsube/neec2019A/files/3295488/_3BaCarnival_20190617.xlsx)

5列目

**Comment by katsube** [comment]
GitHubのリポジトリのURLの提出もお願いしますね。
ここに書いてもらえればOKです。

**Comment by katsube** [comment]
プロダクトバックログの提出もお願いしますねー！
