### ISSUE TITLE
企画書「ナナシのみ」

### ISSUE THREAD

**Issue by YoshiokaTaro** [katsube/neec2019A#36]
[【ナナシのみ】企画書.xlsx](https://github.com/katsube/neec2019A/files/3295659/default.xlsx)

**Comment by katsube** [comment]
座ってる座席の列を記入してください。

**Comment by Walker418** [comment]
5列目の左側の3席に座っています

**Comment by hukihuki** [comment]
[ProductBackLog_0624.xlsx](https://github.com/katsube/neec2019A/files/3319622/ProductBackLog_0624.xlsx)
[チームナナシのみ企画書.xlsx](https://github.com/katsube/neec2019A/files/3319632/default.xlsx)

**Comment by katsube** [comment]
GitHubのリポジトリのURLの提出もお願いしますね。
ここに書いてもらえればOKです。

**Comment by Walker418** [comment]
俨肯壬

お疲れです。Ho Siu Kiです。

GitHubリポジトリの提出を忘れてしまいまして、申しUございません。
リポジトリのURLは以下となります。
https://github.com/Walker418/PongPlus

以上です。

Windows 10 版のメ`ル<https://go.microsoft.com/fwlink/?LinkId=550986>から送信

________________________________
差出人: Makito Katsube <notifications@github.com>
送信日r: Tuesday, July 9, 2019 9:34:36 PM
宛先: katsube/neec2019A
CC: Walker418; Comment
件名: Re: [katsube/neec2019A] 企画弗圣圣筏韦摺 (#36)


GitHubのリポジトリのURLの提出もおいしますね。
ここにい皮猡椁à欷OKです。

―

**Comment by katsube** [comment]
素早い連絡ありがとうー。
リポジトリのURL了解しました。

引き続きがんばってください。
