### ISSUE TITLE
企画書「地獄笠地蔵」

### ISSUE THREAD

**Issue by mheydt1924** [katsube/neec2019A#37]
[企画書_地獄笠地蔵_0624.xlsx](https://github.com/katsube/neec2019A/files/3319396/_._0624.xlsx)

座席
3列目の右半分

**Comment by mheydt1924** [comment]
[企画書_地獄笠地蔵_0624.xlsx](https://github.com/katsube/neec2019A/files/3319584/_._0624.xlsx)
リポジトリURLの追加

**Comment by katsube** [comment]
提出お疲れ様です。
Wikiにも反映しています。

[オンライン対戦](https://github.com/katsube/neec2019A/wiki/%E3%82%AA%E3%83%B3%E3%83%A9%E3%82%A4%E3%83%B3%E5%AF%BE%E6%88%A6)
