### ISSUE TITLE
プロダクトバックログ「地獄笠地蔵」

### ISSUE THREAD

**Issue by mheydt1924** [katsube/neec2019A#38]
[ProductBackLog_地獄笠地蔵_0624.xlsx](https://github.com/katsube/neec2019A/files/3319637/ProductBackLog_._0624.xlsx)

**Comment by katsube** [comment]
拝見しました。
次はこのプロダクトバックログを参考に、自分たちのチームのGitHubのIssueでタスクの登録をお願いしますね。
