### ISSUE TITLE
[ProductBackLog]ポムポムプリン

### ISSUE THREAD

**Issue by Fanogia** [katsube/neec2019A#39]
[ProductBackLog_ポムポムプリン_20190624.xlsx](https://github.com/katsube/neec2019A/files/3319638/ProductBackLog_._20190624.xlsx)

**Comment by katsube** [comment]
拝見しました。
次はこのプロダクトバックログを参考に、自分たちのチームのGitHubのIssueでタスクの登録をお願いしますね。
