### ISSUE TITLE
理解度チェックの提出の件

### ISSUE THREAD

**Issue by sugi23** [katsube/neec2019A#42]
お世話になっております。
日本工学院八王子専門学校 ゲームクリエイター科4年制 杉浦郁哉です。
7月22日に行われた授業内で理解度チェックを提出をしようと思ったのですが16時に教室を訪れた時にはすでに授業が終了していました。
そのため、第2回、第4回の理解度チェックの提出ができませんでした。
対応のほどよろしくお願いします。
あと、第3回の理解度チェックのダウンロードができませんでした。

**Comment by katsube** [comment]
それではスキャンしたファイルをPDFやPNGなどで保存、Zipなどで圧縮し、金曜日中(7/26)にこのIssueへアップロードしてください。今回は受領したいと思います。

また3回目の理解度チェックはこちらの手違いで一時的にダウンロードできない状態にあったようです。こちらは申し訳ないです。

**Comment by sugi23** [comment]
ご対応ありがとうございます。
[理解度チェック_杉浦郁哉.zip](https://github.com/katsube/neec2019A/files/3427182/_.zip)

**Comment by sugi23** [comment]
ご対応ありがとうございます。
下記のzipファイルにまとめさせていただきました。
[rikaido_sugiura.zip](https://github.com/katsube/neec2019A/files/3427210/rikaido_sugiura.zip)

**Comment by katsube** [comment]
受領しました。
10月7日の授業で採点した物を返却しますので、必要でしたら出席してください。

このIssueはクローズします。
